/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scolaire.ihm;

//import java.awt.HeadlessException;
import controllers.AnneeScolaireJpaController;
import entites.AnneeScolaire;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author obama
 */
public class AnneeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AnneeJFrame
     */
    public AnneeJFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("log.png")));
        jButtonEnregistrer.setEnabled(false);
        affichetableAnnee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEntete = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelChamps3 = new javax.swing.JPanel();
        jPanelChamps2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        anneeTable = new javax.swing.JTable();
        anneeFin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        anneeDebut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonModifier = new javax.swing.JButton();
        jButtonEnregistrer = new javax.swing.JButton();
        jButtonNouveau = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 333));
        setPreferredSize(new java.awt.Dimension(450, 333));
        setResizable(false);

        jPanelEntete.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" ANNEE SCOLAIRE");

        javax.swing.GroupLayout jPanelEnteteLayout = new javax.swing.GroupLayout(jPanelEntete);
        jPanelEntete.setLayout(jPanelEnteteLayout);
        jPanelEnteteLayout.setHorizontalGroup(
            jPanelEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnteteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanelEnteteLayout.setVerticalGroup(
            jPanelEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnteteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanelChamps3.setBackground(new java.awt.Color(204, 255, 204));
        jPanelChamps3.setPreferredSize(new java.awt.Dimension(450, 233));
        jPanelChamps3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelChamps2.setBackground(new java.awt.Color(204, 255, 204));

        anneeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Début", "Fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        anneeTable.setColumnSelectionAllowed(true);
        anneeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anneeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(anneeTable);
        anneeTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Début");

        anneeDebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anneeDebutActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fin");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonEnregistrer.setText("Enregistrer");
        jButtonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerActionPerformed(evt);
            }
        });

        jButtonNouveau.setText("Nouveau");
        jButtonNouveau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNouveauMouseClicked(evt);
            }
        });
        jButtonNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNouveauActionPerformed(evt);
            }
        });

        jButtonFermer.setText("Fermer");
        jButtonFermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFermerMouseClicked(evt);
            }
        });
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jButtonNouveau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnregistrer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSupprimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFermer)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSupprimer)
                    .addComponent(jButtonFermer)
                    .addComponent(jButtonEnregistrer)
                    .addComponent(jButtonNouveau))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelChamps2Layout = new javax.swing.GroupLayout(jPanelChamps2);
        jPanelChamps2.setLayout(jPanelChamps2Layout);
        jPanelChamps2Layout.setHorizontalGroup(
            jPanelChamps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChamps2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(anneeDebut)
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anneeFin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(jPanelChamps2Layout.createSequentialGroup()
                .addGroup(jPanelChamps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelChamps2Layout.setVerticalGroup(
            jPanelChamps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChamps2Layout.createSequentialGroup()
                .addGroup(jPanelChamps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(anneeDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(anneeFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelChamps3.add(jPanelChamps2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEntete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelChamps3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEntete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelChamps3, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anneeDebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anneeDebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anneeDebutActionPerformed

    private void jButtonFermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFermerMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonFermerMouseClicked

    private void jButtonNouveauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNouveauMouseClicked
        // TODO add your handling code here:
        anneeDebut.setText("");
        anneeFin.setText("");
    }//GEN-LAST:event_jButtonNouveauMouseClicked

    private void jButtonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerActionPerformed
        // TODO add your handling code here:
        int codeAn=1, debutAn, finAn;

        debutAn = Integer.parseInt(anneeDebut.getText());
        finAn = Integer.parseInt(anneeFin.getText());

//        String req1 = "insert into annee_scolaire (annee_debut,annee_fin) values ('" + debutAn + "','" + finAn + "')";
        String req1 = "insert into annee_scolaire (id_annee_scolaire,annee_debut,annee_fin) values (3,'" + debutAn + "','" + finAn + "')";

        try {
            Connection connexion = Maconnexion.seconnecter();
            Statement instruction = connexion.createStatement();
            int Conf = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment enregistrer ces informations?");
            if (Conf == 0) {
                instruction.executeQuery(req1);
                affichetableAnnee();
                JOptionPane.showMessageDialog(this, "Enregistrement effectué avec succès");
            } else {
                JOptionPane.showMessageDialog(this, "Enregistrement annulé");
            }

            connexion.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erreur: " + e);

        }
        jButtonNouveau.setEnabled(false);
    }//GEN-LAST:event_jButtonEnregistrerActionPerformed

    private void anneeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anneeTableMouseClicked
        // TODO add your handling code here:
        int ligne = anneeTable.getSelectedRow();
//         String unDebut, uneFin;
        //converti et affecte la référence de la pièce justificative du tableau à sa  zone de texte correspondant pour une modification
        Object unDebut = anneeTable.getValueAt(ligne, 1);
        String debut = String.valueOf(unDebut);
        anneeDebut.setText(debut);
        Object fin = anneeTable.getValueAt(ligne, 2);
        String lecycle = String.valueOf(fin);
        anneeFin.setText(lecycle);
        jButtonEnregistrer.setEnabled(false);
    }//GEN-LAST:event_anneeTableMouseClicked

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        // TODO add your handling code here:
        int ligne = anneeTable.getSelectedRow();
//         String unDebut, uneFin;
        Object codeObj = anneeTable.getValueAt(ligne, 0);
        String codeStr = String.valueOf(codeObj);
        int code = Integer.parseInt(codeStr);
//        String code = anneeCode.getText();
        String debutAn = anneeDebut.getText();
        String finAn = anneeFin.getText();
        String req1 = "update annee_scolaire set annee_debut = '" + debutAn + "',annee_fin = '" + finAn + "' where  id_annee_scolaire='" + code + "'";

        try {
            //Class.forName(pilote);
            Connection connexion = Maconnexion.seconnecter();
            Statement instruction = connexion.createStatement();
            int Conf = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier ces informations?");
            if (Conf == 0) {
                instruction.executeQuery(req1);
                affichetableAnnee();
//                instruction.executeQuery(req2);
                JOptionPane.showMessageDialog(this, "Modification effectuée avec succès");
            } else {
                JOptionPane.showMessageDialog(this, "Modification annulée");
            }

            connexion.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erreur: " + e);

        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed

        int ligne = anneeTable.getSelectedRow();
        Object idAnneeObj = anneeTable.getValueAt(ligne, 0);
        String idAnneeStr = String.valueOf(idAnneeObj);
        int idAnnee = Integer.parseInt(idAnneeStr);

        String req1 = "delete from annee_scolaire where  id_annee_scolaire='" + idAnnee + "'";

        try {

            try (Connection connexion = Maconnexion.seconnecter()) {
                Statement instruction = connexion.createStatement();
                int Conf = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer ces informations?");
                if (Conf == 0) {
                    instruction.executeQuery(req1);
                    affichetableAnnee();
//                instruction.executeQuery(req2);
                    JOptionPane.showMessageDialog(this, "Suppression effectuée avec succès");
                } else {
                    JOptionPane.showMessageDialog(this, "Suppression annulée");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Impossible de supprimer cette année car elle contient des Trimestres " + e);

        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonFermerActionPerformed

    private void jButtonNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNouveauActionPerformed
        // TODO add your handling code here:
        jButtonEnregistrer.setEnabled(true);
    }//GEN-LAST:event_jButtonNouveauActionPerformed

    //méthode pour l'affichge du tableau Serie'
    private void affichetableAnnee() {
//       String pilote = "oracle.jdbc.driver.OracleDriver";
//         String pilote = "org.postgresql.Driver";
        DefaultTableModel model = new DefaultTableModel();
        anneeTable.setModel(model); //affectation du model au tableau
        model.addColumn("Code");
        model.addColumn("Début");
        model.addColumn("Fin");

        TableColumn column, column1, column2 = null;
        column = anneeTable.getColumnModel().getColumn(0);
        column.setPreferredWidth(90); //
        column1 = anneeTable.getColumnModel().getColumn(1);
        column1.setPreferredWidth(300); //
        column2 = anneeTable.getColumnModel().getColumn(2);
        column2.setPreferredWidth(300); //
        // pour eviter des probleme avec postgres les table doit etre en miniscule
//        JOptionPane.showMessageDialog(this, "affichetableAnnee : Avant le try ");
        try {
//            JOptionPane.showMessageDialog(this, "affichetableAnnee : debut try ");
            Connection connexion = Maconnexion.seconnecter();
//            JOptionPane.showMessageDialog(this, "apres connexion");
            Statement instruction = connexion.createStatement();
//            JOptionPane.showMessageDialog(this, "apres statement");
            String req = "SELECT * FROM public.annee_scolaire";
            ResultSet resultat = instruction.executeQuery(req);
//            JOptionPane.showMessageDialog(this, "apres resultSet");
            int i = 0;
//            JOptionPane.showMessageDialog(this, "affichetableAnneehetableAnnee : Avant le while ");
            while (resultat.next()) {
                String codeAnnee = resultat.getString("id_annee_scolaire");
                String debutAnnee = resultat.getString("annee_debut");
                String finAnnee = resultat.getString("annee_fin");
//                String unefamille=resultat.getString("LIBELLE_FAMILLE");
//                table2.setValueAt(unnum,i,0);
//                table2.setValueAt(unefamille,i,1);
//                table2.setValueAt(untype,i,2);
//                AnneeScolaireJpaController anneeScolaireJpaController = null;
//                List<AnneeScolaire> listAnneeScolaire;
//                try {
//                    listAnneeScolaire = anneeScolaireJpaController.findAnneeScolaireEntities();
//                } catch (Exception e) {
//                }
//              model.addRow(new Object[]{codeAnnee, debutAnnee, finAnnee});
                model.addRow(new Object[]{codeAnnee, debutAnnee, finAnnee});
                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "affichetableAnnee : " + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnneeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnneeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnneeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnneeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnneeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anneeDebut;
    private javax.swing.JTextField anneeFin;
    private javax.swing.JTable anneeTable;
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonNouveau;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelChamps2;
    private javax.swing.JPanel jPanelChamps3;
    private javax.swing.JPanel jPanelEntete;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
