/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scolaire.ihm;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author obama
 */
public class CoefficientJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AnneeJFrame
     */
    public CoefficientJFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("log.png")));
//        affichetableCoeffficient();
        affichetableMatiere();
        affichetableGp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEntete = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelChamps = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        groupPedagTable = new javax.swing.JTable();
        jPanelTrimestre = new javax.swing.JPanel();
        jPanelChamps3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        coefficientTable = new javax.swing.JTable();
        jPanelChamps4 = new javax.swing.JPanel();
        valCoef = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanelBoutons1 = new javax.swing.JPanel();
        jButtonFermer2 = new javax.swing.JButton();
        jButtonNouveau1 = new javax.swing.JButton();
        jButtonEnregistrer = new javax.swing.JButton();
        buttonModifierCycle1 = new javax.swing.JButton();
        jButtonSupprimer2 = new javax.swing.JButton();
        jPanelChamps2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        matiereTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelEntete.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COEFFICIENTS");

        javax.swing.GroupLayout jPanelEnteteLayout = new javax.swing.GroupLayout(jPanelEntete);
        jPanelEntete.setLayout(jPanelEnteteLayout);
        jPanelEnteteLayout.setHorizontalGroup(
            jPanelEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnteteLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelEnteteLayout.setVerticalGroup(
            jPanelEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnteteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelChamps.setBackground(new java.awt.Color(204, 255, 204));
        jPanelChamps.setBorder(javax.swing.BorderFactory.createTitledBorder("Groupes Pédagogiques"));

        groupPedagTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Abréviation", "Libellé"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        groupPedagTable.setColumnSelectionAllowed(true);
        groupPedagTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupPedagTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(groupPedagTable);
        groupPedagTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanelChampsLayout = new javax.swing.GroupLayout(jPanelChamps);
        jPanelChamps.setLayout(jPanelChampsLayout);
        jPanelChampsLayout.setHorizontalGroup(
            jPanelChampsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChampsLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelChampsLayout.setVerticalGroup(
            jPanelChampsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChampsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelChamps3.setBackground(new java.awt.Color(204, 255, 204));
        jPanelChamps3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des coefficients", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 51))); // NOI18N

        coefficientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Grp. Pédagogique", "Matière", "Coefficient"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        coefficientTable.setColumnSelectionAllowed(true);
        coefficientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coefficientTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(coefficientTable);
        coefficientTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanelChamps3Layout = new javax.swing.GroupLayout(jPanelChamps3);
        jPanelChamps3.setLayout(jPanelChamps3Layout);
        jPanelChamps3Layout.setHorizontalGroup(
            jPanelChamps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChamps3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanelChamps3Layout.setVerticalGroup(
            jPanelChamps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChamps3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );

        jPanelChamps4.setBackground(new java.awt.Color(204, 255, 204));
        jPanelChamps4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coefficient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 51))); // NOI18N

        valCoef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valCoefActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Coefficient");

        javax.swing.GroupLayout jPanelChamps4Layout = new javax.swing.GroupLayout(jPanelChamps4);
        jPanelChamps4.setLayout(jPanelChamps4Layout);
        jPanelChamps4Layout.setHorizontalGroup(
            jPanelChamps4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChamps4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valCoef, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelChamps4Layout.setVerticalGroup(
            jPanelChamps4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChamps4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelChamps4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valCoef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelBoutons1.setBackground(new java.awt.Color(204, 255, 204));
        jPanelBoutons1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 51))); // NOI18N

        jButtonFermer2.setText("Fermer");
        jButtonFermer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFermer2MouseClicked(evt);
            }
        });
        jButtonFermer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermer2ActionPerformed(evt);
            }
        });

        jButtonNouveau1.setText("Nouveau");
        jButtonNouveau1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButtonNouveau1StateChanged(evt);
            }
        });
        jButtonNouveau1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNouveau1MouseClicked(evt);
            }
        });
        jButtonNouveau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNouveau1ActionPerformed(evt);
            }
        });

        jButtonEnregistrer.setText("Enregistrer");
        jButtonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerActionPerformed(evt);
            }
        });

        buttonModifierCycle1.setText("Modifier");
        buttonModifierCycle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifierCycle1ActionPerformed(evt);
            }
        });

        jButtonSupprimer2.setText("Supprimer");
        jButtonSupprimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimer2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBoutons1Layout = new javax.swing.GroupLayout(jPanelBoutons1);
        jPanelBoutons1.setLayout(jPanelBoutons1Layout);
        jPanelBoutons1Layout.setHorizontalGroup(
            jPanelBoutons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoutons1Layout.createSequentialGroup()
                .addComponent(jButtonNouveau1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonModifierCycle1)
                .addGap(14, 14, 14)
                .addComponent(jButtonSupprimer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFermer2)
                .addGap(23, 23, 23))
        );
        jPanelBoutons1Layout.setVerticalGroup(
            jPanelBoutons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBoutons1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelBoutons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFermer2)
                    .addComponent(jButtonNouveau1)
                    .addComponent(jButtonEnregistrer)
                    .addComponent(buttonModifierCycle1)
                    .addComponent(jButtonSupprimer2)))
        );

        javax.swing.GroupLayout jPanelTrimestreLayout = new javax.swing.GroupLayout(jPanelTrimestre);
        jPanelTrimestre.setLayout(jPanelTrimestreLayout);
        jPanelTrimestreLayout.setHorizontalGroup(
            jPanelTrimestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBoutons1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrimestreLayout.createSequentialGroup()
                .addGroup(jPanelTrimestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelChamps3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelChamps4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanelTrimestreLayout.setVerticalGroup(
            jPanelTrimestreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrimestreLayout.createSequentialGroup()
                .addComponent(jPanelChamps4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelChamps3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanelBoutons1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelChamps2.setBackground(new java.awt.Color(204, 255, 204));
        jPanelChamps2.setBorder(javax.swing.BorderFactory.createTitledBorder("Matières"));

        matiereTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Code", "Promotion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        matiereTable.setColumnSelectionAllowed(true);
        matiereTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matiereTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(matiereTable);
        matiereTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (matiereTable.getColumnModel().getColumnCount() > 0) {
            matiereTable.getColumnModel().getColumn(0).setHeaderValue("Code");
            matiereTable.getColumnModel().getColumn(1).setHeaderValue("Promotion");
        }

        javax.swing.GroupLayout jPanelChamps2Layout = new javax.swing.GroupLayout(jPanelChamps2);
        jPanelChamps2.setLayout(jPanelChamps2Layout);
        jPanelChamps2Layout.setHorizontalGroup(
            jPanelChamps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChamps2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
        );
        jPanelChamps2Layout.setVerticalGroup(
            jPanelChamps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChamps2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelChamps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelChamps2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTrimestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEntete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEntete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelChamps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelChamps2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelTrimestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matiereTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matiereTableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_matiereTableMouseClicked

    private void groupPedagTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupPedagTableMouseClicked
        // TODO add your handling code here:
        // Récupération du groupe pédagogique depuis la table groupPedagTable;
        try {
            int ligneGp = groupPedagTable.getSelectedRow();
            Object idGpObj = groupPedagTable.getValueAt(ligneGp, 0);
            String idGpStr = String.valueOf(idGpObj);
            idGp = Integer.parseInt(idGpStr);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Aucun groupe pédagogique n'a été sélectionné ");
        }
        affichetableCoeffficient(idGp);
    }//GEN-LAST:event_groupPedagTableMouseClicked

    private void jButtonSupprimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimer2ActionPerformed
        // TODO add your handling code here:
        // Récupération du groupe pédagogique depuis la table groupPedagTable;
        try {
            int ligneGp = groupPedagTable.getSelectedRow();
            Object idGpObj = groupPedagTable.getValueAt(ligneGp, 0);
            String idGpStr = String.valueOf(idGpObj);
            idGp = Integer.parseInt(idGpStr);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Aucun groupe pédagogique n'a été sélectionné ");
        }
        // Récupération de l'id de la promotion depuis la table groupePedagTable
        int ligneCoef = coefficientTable.getSelectedRow();
        Object idCoefObj = coefficientTable.getValueAt(ligneCoef, 0);
        String idCoefStr = String.valueOf(idCoefObj);
        int idCoef = Integer.parseInt(idCoefStr);
        String req1 = "delete from COEFFICIENT where  ID_COEF='" + idCoef + "'";
        try {
            Connection connexion = Maconnexion.seconnecter();
            Statement instruction = connexion.createStatement();
            int Conf = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer ces informations?");
            if (Conf == 0) {
                instruction.executeQuery(req1);
                affichetableCoeffficient(idGp);
                valCoef.setText("");
                jButtonEnregistrer.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Suppression effectuée avec succès");
            } else {
                JOptionPane.showMessageDialog(this, "Suppression annulée");
            }
            connexion.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erreur: " + e);
        }
    }//GEN-LAST:event_jButtonSupprimer2ActionPerformed

    private void buttonModifierCycle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifierCycle1ActionPerformed
        // TODO add your handling code here:
        // Récupération du groupe pédagogique depuis la table groupPedagTable;
        try {
            int ligneGp = groupPedagTable.getSelectedRow();
            Object idGpObj = groupPedagTable.getValueAt(ligneGp, 0);
            String idGpStr = String.valueOf(idGpObj);
            idGp = Integer.parseInt(idGpStr);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Aucun groupe pédagogique n'a été sélectionné ");
        }
        // Récupération de l'id de la série depuis la table serieTable
        int ligneCoef = coefficientTable.getSelectedRow();
        Object idCoefObj = coefficientTable.getValueAt(ligneCoef, 0);
        String idCoefStr = String.valueOf(idCoefObj);
        int idCoef = Integer.parseInt(idCoefStr);

        String req = "update COEFFICIENT set VALEUR_COEF = '" + valCoef.getText() + "' where  ID_COEF = '" + idCoef + "'";

        try {
            Connection connexion = Maconnexion.seconnecter();
            Statement instruction = connexion.createStatement();
            int Conf = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier ces informations?");
            if (Conf == 0) {
                instruction.executeQuery(req);
                affichetableCoeffficient(idGp);
                valCoef.setText("");
                jButtonEnregistrer.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Modification effectuée avec succès");
            } else {
                JOptionPane.showMessageDialog(this, "Modification annulée");
            }

            connexion.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erreur: " + e);

        }
    }//GEN-LAST:event_buttonModifierCycle1ActionPerformed

    private void jButtonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerActionPerformed
        // TODO add your handling code here:

        // Récupération du groupe pédagogique depuis la table groupPedagTable;
        try {
            int ligneGp = groupPedagTable.getSelectedRow();
            Object idGpObj = groupPedagTable.getValueAt(ligneGp, 0);
            String idGpStr = String.valueOf(idGpObj);
            idGp = Integer.parseInt(idGpStr);
            // Récupération de la matière depuis la table matiereTable;
            try {
                int ligneMat = matiereTable.getSelectedRow();
                Object idMatObj = matiereTable.getValueAt(ligneMat, 0);
                String idMatStr = String.valueOf(idMatObj);
                idMat = Integer.parseInt(idMatStr);
//                enregGp();
                // Insertion d'un coefficient dans la table COEFFICIENT 
                String req1 = "insert into COEFFICIENT (VALEUR_COEF,ID_GROUP_PEDAG,ID_MATIERE) values ('" + valCoef.getText() + "', '" + idGp + "','" + idMat + "')";
                try {
                    Connection connexion = Maconnexion.seconnecter();
                    Statement instruction = connexion.createStatement();
                    int Conf = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment ajouter ce coefficient ?");
                    if (Conf == 0) {
                        instruction.executeQuery(req1);
                        JOptionPane.showMessageDialog(this, "Enregistrement effectué avec succès");
                        affichetableCoeffficient(idGp);
                    } else {
                        JOptionPane.showMessageDialog(this, "Enregistrement annulé");
                    }
                    connexion.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "erreur: " + e);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, " Aucune matière n'a été sélectionnée ");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " Aucun groupe pédagogique n'a été sélectionné ");
        }


    }//GEN-LAST:event_jButtonEnregistrerActionPerformed

    private void jButtonNouveau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNouveau1ActionPerformed
        // TODO add your handling code here:
        valCoef.setText("");
        jButtonEnregistrer.setEnabled(true);
    }//GEN-LAST:event_jButtonNouveau1ActionPerformed

    private void jButtonNouveau1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNouveau1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNouveau1MouseClicked

    private void jButtonNouveau1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButtonNouveau1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNouveau1StateChanged

    private void jButtonFermer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermer2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonFermer2ActionPerformed

    private void jButtonFermer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFermer2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFermer2MouseClicked

    private void valCoefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valCoefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valCoefActionPerformed

    private void coefficientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coefficientTableMouseClicked
        // TODO add your handling code here:
        int ligne = coefficientTable.getSelectedRow();
        Object coefObj = coefficientTable.getValueAt(ligne, 3);
        String coef = String.valueOf(coefObj);
        valCoef.setText(coef);
        jButtonEnregistrer.setEnabled(false);
    }//GEN-LAST:event_coefficientTableMouseClicked
    int idGp = 0;
    int idMat = 0;

    //méthode pour l'affichge du tableau coefficientTable'
    private void affichetableCoeffficient(int idGp) {

        DefaultTableModel model = new DefaultTableModel();
        coefficientTable.setModel(model); //affectation du model au tableau
        model.addColumn("Code");
        model.addColumn("Groupe Pédagogique");
        model.addColumn("Matière");
        model.addColumn("Coefficient");
        TableColumn column, column1, column2, column3 = null;
        column = coefficientTable.getColumnModel().getColumn(0);
        column.setPreferredWidth(40); //
        column1 = coefficientTable.getColumnModel().getColumn(1);
        column1.setPreferredWidth(300); //
        column2 = coefficientTable.getColumnModel().getColumn(2);
        column2.setPreferredWidth(300); //
        column3 = coefficientTable.getColumnModel().getColumn(3);
        column3.setPreferredWidth(40); //
        try {
            Connection connexion = Maconnexion.seconnecter();
            Statement instruction = connexion.createStatement();
            ResultSet resultat = instruction.executeQuery("select ID_COEF, GROUP_PEDAG_ABREV, LIB_GROUP_PEDAG, LIB_MATIERE, VALEUR_COEF from COEFFICIENT, GROUP_PEDAG, MATIERE"
                    + " where COEFFICIENT.ID_GROUP_PEDAG = GROUP_PEDAG.ID_GROUP_PEDAG "
                    + " and COEFFICIENT.ID_MATIERE = MATIERE.ID_MATIERE"
                    + " and COEFFICIENT.ID_GROUP_PEDAG = '" + idGp + "'");
            while (resultat.next()) {
                int idCoef = resultat.getInt("ID_COEF");
                String groupPedag = resultat.getString("GROUP_PEDAG_ABREV");
                String mat = resultat.getString("LIB_MATIERE");
                int coef = resultat.getInt("VALEUR_COEF");
                model.addRow(new Object[]{idCoef, groupPedag, mat, coef});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erreur3: " + e);
        }

    }

    //méthode pour l'affichge du tableau matiereTable'
    private void affichetableMatiere() {
//       String pilote = "oracle.jdbc.driver.OracleDriver";
        DefaultTableModel model = new DefaultTableModel();
        matiereTable.setModel(model); //affectation du model au tableau
        model.addColumn("Code");
        model.addColumn("Libellé");

        TableColumn column, column1 = null;
        column = matiereTable.getColumnModel().getColumn(0);
        column.setPreferredWidth(90); //
        column1 = matiereTable.getColumnModel().getColumn(1);
        column1.setPreferredWidth(300); //

        try {
            Connection connexion = Maconnexion.seconnecter();
            Statement instruction = connexion.createStatement();
            ResultSet resultat = instruction.executeQuery("select * from MATIERE");
//            int i = 0;
            while (resultat.next()) {
                int codeMatiere = resultat.getInt("ID_MATIERE");
                String libMatiere = resultat.getString("LIB_MATIERE");
                model.addRow(new Object[]{codeMatiere, libMatiere});
//                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erreur3: " + e);
        }
    }

    //méthode pour l'affichge du tableau Serie'
    private void affichetableGp() {
//       String pilote = "oracle.jdbc.driver.OracleDriver";
        DefaultTableModel model = new DefaultTableModel();
        groupPedagTable.setModel(model); //affectation du model au tableau
        model.addColumn("Code");
        model.addColumn("Abréviation");
        model.addColumn("Grp. Pédagogique");

        TableColumn column, column1, column2 = null;
        column = groupPedagTable.getColumnModel().getColumn(0);
        column.setPreferredWidth(90); //
        column1 = groupPedagTable.getColumnModel().getColumn(1);
        column1.setPreferredWidth(100); //
        column2 = groupPedagTable.getColumnModel().getColumn(2);
        column2.setPreferredWidth(300); //
        try {
            Connection connexion = Maconnexion.seconnecter();
            Statement instruction = connexion.createStatement();
            ResultSet resultat = instruction.executeQuery("select * from GROUP_PEDAG");
//            int i = 0;
            while (resultat.next()) {
                int idGp = resultat.getInt("ID_GROUP_PEDAG");
                String abrevGp = resultat.getString("GROUP_PEDAG_ABREV");
                String libGp = resultat.getString("LIB_GROUP_PEDAG");

                model.addRow(new Object[]{idGp, abrevGp, libGp});
//                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erreur3: " + e);
        }
    }

    public void enregGp() {

        int idGroupPedag = 0;
        int idMatiere = 0;
        // Récupération du groupe pédagogique depuis la table groupPedagTable;
        int ligneGp = groupPedagTable.getSelectedRow();
        Object idGpObj = groupPedagTable.getValueAt(ligneGp, 0);
        String idGpStr = String.valueOf(idGpObj);
        idGroupPedag = Integer.parseInt(idGpStr);
        if (idGroupPedag == 0) {
            JOptionPane.showMessageDialog(this, " Aucun groupe pédagogique n'a été sélectionnée ");
        }
        // Récupération de la matière depuis la table matiereTable;
        int ligneMat = matiereTable.getSelectedRow();
        Object idMatObj = matiereTable.getValueAt(ligneMat, 0);
        String idMatStr = String.valueOf(idMatObj);
        idMatiere = Integer.parseInt(idMatStr);

        try {
            Connection connexion = Maconnexion.seconnecter();
            String req = "INSERT INTO COEFFICIENT (VALEUR_COEF,ID_MATIERE,ID_GROUP_PEDAG) VALUES ('" + valCoef.getText() + "','" + idMatiere + "','" + idGroupPedag + "')";
            Statement instruction = connexion.createStatement();
            instruction.executeQuery(req);
            affichetableCoeffficient(idGp);
            JOptionPane.showMessageDialog(this, "Enregistrement effectué avec succès");
            connexion.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erreur: " + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoefficientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoefficientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoefficientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoefficientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoefficientJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonModifierCycle1;
    private javax.swing.JTable coefficientTable;
    private javax.swing.JTable groupPedagTable;
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JButton jButtonFermer2;
    private javax.swing.JButton jButtonNouveau1;
    private javax.swing.JButton jButtonSupprimer2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelBoutons1;
    private javax.swing.JPanel jPanelChamps;
    private javax.swing.JPanel jPanelChamps2;
    private javax.swing.JPanel jPanelChamps3;
    private javax.swing.JPanel jPanelChamps4;
    private javax.swing.JPanel jPanelEntete;
    private javax.swing.JPanel jPanelTrimestre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable matiereTable;
    private javax.swing.JTextField valCoef;
    // End of variables declaration//GEN-END:variables
}
