/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scolaire.ihm;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author obama
 */
public class SerieJFrame extends javax.swing.JFrame {

    /**
     * Creates new form Serie
     */
    public SerieJFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("log.png")));
        affichetableSerie();
    }

    public void affichetableSerie() {
        DefaultTableModel model = new DefaultTableModel();
        serieTable.setModel(model); //affectation du model au tableau
        model.addColumn("Code");
        model.addColumn("Abréviation");
        model.addColumn("Promotion");
        model.addColumn("idSerie");
        model.addColumn("idCycle");
        TableColumn column, column1, column2, column3, column4 = null;
        column = serieTable.getColumnModel().getColumn(0);
        column.setPreferredWidth(90); //
        column1 = serieTable.getColumnModel().getColumn(1);
        column1.setPreferredWidth(300); //
//        column2 = serieTable.getColumnModel().getColumn(2);
//        column2.setPreferredWidth(300); //
//        column3 = serieTable.getColumnModel().getColumn(3);
//        column3.setPreferredWidth(300); //
//        column4 = promotionTable.getColumnModel().getColumn(4);
//        column4.setPreferredWidth(300); //
        try {
            Connection connexion = Maconnexion.seconnecter();
            Statement instruction = connexion.createStatement();
            ResultSet resultat = instruction.executeQuery("select * from SERIE");
            int i = 0;
            while (resultat.next()) {
//                String codePromotion = resultat.getString("ID_SERIE");
//                String abrevPromo = resultat.getString("PROMO_ABREV");
//                String idCycle = resultat.getString("ID_CYCLES");
                String libSerie = resultat.getString("LIB_SERIE");
                String idSerie = resultat.getString("ID_SERIE");
                model.addRow(new Object[]{idSerie, libSerie});
                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erreur3: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEntete = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelChamps1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        libelleSerie = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        serieTable = new javax.swing.JTable();
        jButtonNouveau1 = new javax.swing.JButton();
        jButtonEnregistrer1 = new javax.swing.JButton();
        jButtonModifier1 = new javax.swing.JButton();
        jButtonSupprimer1 = new javax.swing.JButton();
        jButtonFermer1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelEntete.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SERIE");

        javax.swing.GroupLayout jPanelEnteteLayout = new javax.swing.GroupLayout(jPanelEntete);
        jPanelEntete.setLayout(jPanelEnteteLayout);
        jPanelEnteteLayout.setHorizontalGroup(
            jPanelEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEnteteLayout.setVerticalGroup(
            jPanelEnteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnteteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelChamps1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Série");

        javax.swing.GroupLayout jPanelChamps1Layout = new javax.swing.GroupLayout(jPanelChamps1);
        jPanelChamps1.setLayout(jPanelChamps1Layout);
        jPanelChamps1Layout.setHorizontalGroup(
            jPanelChamps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChamps1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(libelleSerie)
                .addContainerGap())
        );
        jPanelChamps1Layout.setVerticalGroup(
            jPanelChamps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChamps1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelChamps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(libelleSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        serieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Code", "Libellé"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        serieTable.setColumnSelectionAllowed(true);
        serieTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serieTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(serieTable);

        jButtonNouveau1.setText("Nouveau");
        jButtonNouveau1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNouveau1MouseClicked(evt);
            }
        });

        jButtonEnregistrer1.setText("Enregistrer");
        jButtonEnregistrer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrer1ActionPerformed(evt);
            }
        });

        jButtonModifier1.setText("Modifier");
        jButtonModifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifier1ActionPerformed(evt);
            }
        });

        jButtonSupprimer1.setText("Supprimer");
        jButtonSupprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimer1ActionPerformed(evt);
            }
        });

        jButtonFermer1.setText("Fermer");
        jButtonFermer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFermer1MouseClicked(evt);
            }
        });
        jButtonFermer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEntete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelChamps1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNouveau1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEnregistrer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonModifier1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSupprimer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFermer1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEntete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelChamps1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier1)
                    .addComponent(jButtonSupprimer1)
                    .addComponent(jButtonFermer1)
                    .addComponent(jButtonNouveau1)
                    .addComponent(jButtonEnregistrer1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serieTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serieTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_serieTableMouseClicked

    private void jButtonNouveau1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNouveau1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNouveau1MouseClicked

    private void jButtonEnregistrer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrer1ActionPerformed
        // TODO add your handling code here:
        String libSerie = libelleSerie.getText();
        if (libSerie.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Le libellé de la série est obligatoire.");
        } else {
            String req = "insert into SERIE (LIB_SERIE) values ('" + libSerie + "')";
            try {
                Connection connexion = Maconnexion.seconnecter();
                Statement instruction = connexion.createStatement();
                int Conf = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment enregistrer ces informations?");
                if (Conf == 0) {
                    instruction.executeQuery(req);
                    JOptionPane.showMessageDialog(this, "Enregistrement effectué avec succès");
                    affichetableSerie();
                } else {
                    JOptionPane.showMessageDialog(this, "Enregistrement annulé");
                }
                connexion.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "erreur: " + e);
            }
        }
    }//GEN-LAST:event_jButtonEnregistrer1ActionPerformed

    private void jButtonModifier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifier1ActionPerformed
        // TODO add your handling code here:
        int ligne = serieTable.getSelectedRow();
        int idSerie = (int) serieTable.getValueAt(ligne, 0);
        String libSerie = libelleSerie.getText().trim();
        String req = "update SERIE set LIB_SERIE = '" + libSerie + "' WHERE ID_SERIE = '" + idSerie + "'";
        try {
            Connection connexion = Maconnexion.seconnecter();
            Statement instruction = connexion.createStatement();
            int Conf = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment enregistrer ces informations?");
            if (Conf == 0) {
                instruction.executeQuery(req);
                JOptionPane.showMessageDialog(this, "Modification effectuée avec succès");
                affichetableSerie();
            } else {
                JOptionPane.showMessageDialog(this, "Modification annulée");
            }
            connexion.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erreur: " + e);
        }
    }//GEN-LAST:event_jButtonModifier1ActionPerformed

    private void jButtonSupprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimer1ActionPerformed
        // TODO add your handling code here:
        int ligne = serieTable.getSelectedRow();
        int idSerie = (int) serieTable.getValueAt(ligne, 0);
        String libSerie = libelleSerie.getText().trim();
        String req = "delete from SERIE WHERE ID_SERIE = '" + idSerie + "'";
        try {
            Connection connexion = Maconnexion.seconnecter();
            Statement instruction = connexion.createStatement();
            int Conf = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment Supprimer ces informations?");
            if (Conf == 0) {
                instruction.executeQuery(req);
                JOptionPane.showMessageDialog(this, "Suppression effectuée avec succès");
                affichetableSerie();
            } else {
                JOptionPane.showMessageDialog(this, "Suppression annulée");
            }
            connexion.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erreur: " + e);
        }
    }//GEN-LAST:event_jButtonSupprimer1ActionPerformed

    private void jButtonFermer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFermer1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFermer1MouseClicked

    private void jButtonFermer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermer1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonFermer1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SerieJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SerieJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SerieJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SerieJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SerieJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnregistrer1;
    private javax.swing.JButton jButtonFermer1;
    private javax.swing.JButton jButtonModifier1;
    private javax.swing.JButton jButtonNouveau1;
    private javax.swing.JButton jButtonSupprimer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelChamps1;
    private javax.swing.JPanel jPanelEntete;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField libelleSerie;
    private javax.swing.JTable serieTable;
    // End of variables declaration//GEN-END:variables
}
